site_name: Tabeçaí

repo_name: '2023.2-Tabecai'
repo_url: 'https://github.com/mdsreq-fga-unb/2023.2-Tabecai'

theme:
  name: material

site_description: Este repositório é dedicado ao projeto da Turma 4 da disciplina de Requisitos de Software, ministrada pelo professor George Marsicano, no segundo semestre de 2023 na Universidade de Brasília. Nosso grupo, chamado 'Tabeça Team', foca na resolução do problema de Gestão do Fluxo de Caixa em lojas de uma empresa de açaí. Atualmente, esse processo é manual, realizado no Excel pelo departamento financeiro. Nosso objetivo é eliminar essa dependência de processos manuais e desenvolver uma solução eficaz para o registro de pagamentos a prazo. Neste repositório, você encontrará nossa documentação e progresso no desenvolvimento dessa solução.

nav:
  - Home: index.md

  - Documentação:
      - Visão de Produto: 'visao-produto.md' #ok
      - Visão de Projeto: 'visão-projeto.md' # FALTA ATUALIZAR O PLANEJAMENTO SPRINT (MVP1 e 2)
      - Processo: 'processo.md' #ok
      - BackLog do Produto: 'backlog_produto.md' #ok
      - MVPS`s: 'mvp.md' #ok
      - Soluções de Software : 'processoSoftware.md'

      - PBB e BDD HealthNet: 'pbb_heatnet.md'
      - USM ComunEventos : 'usm_comuneventos.md'
      - Caso de Uso _____ : 'casoUso.md'
            # terminar no miro !!!!!    
  - Entregas:
      - Unidade 1: 'entrega_1.md'
      - Unidade 2: 'entrega_2.md'
      - Unidade 3: 'entrega_3.md'
      - Unidade 3: 'entrega_4.md'
  - Lições Aprendidas:
      - Unidade 1: 'lessons.md'
      - Unidade 2: 'lessons.md'
      - Unidade 3: 'lessons.md'
