version: "3.1"

services:
  tabecai-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabecai-api
    restart: always
    depends_on:
      - tabecai-database
    ports:
      - 3535:3535
    volumes:
      - .:/home/app
    working_dir: /home/app

  tabecai-database:
    container_name: tabecai-database
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tabecai_password
      POSTGRES_USER: tabecai_user
      POSTGRES_DB: tabecai_database
    ports:
      - 5432:5432
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
