version: '3.1'

services:
  tabecai-database:
    image: postgres:alpine
    ports:
      - '5435:5432'
    container_name: tabecai-database
    restart: always
    volumes:
      - ./banco-de-dados-tabecai:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=tabecai_database
  tabecai-api:
    build: .
    container_name: tabecai-api
    ports:
      - 3333:3333
      - 5555:5555
    restart: always
    volumes:
      - .:/usr/app
    depends_on:
      - tabecai-database

volumes:
  banco-de-dados-tabecai:
